language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

after_failure:
  - cat target/surefire-reports/*.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
